import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkLoaded, ClerkProvider, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex items-center justify-between h-20 fixed top-0 left-0 w-full px-4 border-b rounded-b-lg shadow-md bg-white">
            <Link href="/">
              <h1 className="font-bold">Poke Collection</h1>
            </Link>
            <nav>
              <ClerkLoaded>
                <UserButton />
              </ClerkLoaded>
            </nav>
          </header>
          <div className="mt-20">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
