import "./globals.css";

import { ClerkLoaded, ClerkProvider, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import { DesktopNav } from "@/components/shared/desktop-nav";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="fixed left-0 top-0 flex h-20 w-full items-center rounded-b-lg border-b bg-white px-4 shadow-md">
            <div className="mx-auto flex w-full max-w-[1024px] items-center justify-between">
              <Link href="/">
                <h1 className="font-bold">Poke Collection</h1>
              </Link>
              <DesktopNav className="hidden md:block" />
              <ClerkLoaded>
                <UserButton />
              </ClerkLoaded>
            </div>
          </header>
          <div className="mx-auto mt-20 max-w-[1024px] px-4 py-6 md:px-0">
            {children}
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
