import "./globals.css";

import { ClerkLoaded, ClerkProvider, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import { DesktopNav } from "@/components/shared/desktop-nav";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="h-20 fixed top-0 left-0 w-full px-4 border-b rounded-b-lg shadow-md bg-white flex items-center">
            <div className="max-w-[1024px] flex items-center justify-between w-full mx-auto">
              <Link href="/">
                <h1 className="font-bold">Poke Collection</h1>
              </Link>
              <DesktopNav className="hidden md:block" />
              <ClerkLoaded>
                <UserButton />
              </ClerkLoaded>
            </div>
          </header>
          <div className="mt-20 py-6 max-w-[1024px] mx-auto px-4 md:px-0">
            {children}
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
